name: CI

on:
  pull_request:
    branches: [main, foundations]
  push:
    branches: [main, foundations]

jobs:
  test:
    runs-on:
      group: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Build application
        run: npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: matrix.node-version == '20.x'
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  docker-build:
    runs-on:
      group: self-hosted
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t kometa-dashboard:${{ github.sha }} .

      - name: Test Docker image
        run: |
          docker run --rm -d --name test-container -p 3001:3000 kometa-dashboard:${{ github.sha }}
          sleep 10
          curl -f http://localhost:3001 || exit 1
          docker stop test-container

      - name: Clean up Docker image
        run: docker rmi kometa-dashboard:${{ github.sha }}
