name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

jobs:
  pr-title-check:
    runs-on:
      group: self-hosted

    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;

            // Valid patterns:
            // - "Complete Task X.X: Description"
            // - "Day X: Description" 
            // - "Fix: Description"
            // - "Update: Description"
            // - "Add: Description"
            const validPatterns = [
              /^Complete Task \d+\.\d+: .+/,
              /^Day \d+: .+/,
              /^(Fix|Update|Add|Refactor|Test|Docs): .+/i
            ];

            const isValid = validPatterns.some(pattern => pattern.test(title));

            if (!isValid) {
              core.setFailed(`
                PR title "${title}" does not follow the required format.
                
                Valid formats:
                - "Complete Task X.X: Description"
                - "Day X: Description"  
                - "Fix: Description"
                - "Update: Description"
                - "Add: Description"
                - "Refactor: Description"
                - "Test: Description"
                - "Docs: Description"
              `);
            } else {
              console.log(`PR title "${title}" is valid.`);
            }
